name: Hello World Workflow
on:
  push:
    branches:
      - master
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python hello.py
      - run: python newFile.py